name: CMake

on: [push, pull_request, workflow_dispatch]

# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        uname -a
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install gcc-multilib g++-multilib lcov ccache valgrind libgcc-s1:i386 libc6-dbg:i386
        sudo pip install empy pydronecan
    - name: Submodule update
      run: |
        git submodule update --init --recursive
    - name: Run Tests for canard_c library
      working-directory: ${{github.workspace}}
      run: ./run_test.sh
    - name: show coverage results
      working-directory: ${{github.workspace}}
      run: lcov --list coverage.info
